#!/bin/bash
# scripts/edit_production_db_gate_notes.sh
# Phase 6T - Instructions for setting up DB gate safely

echo "============================================================"
echo "    Production DB Read-Only Gate Instructions (Phase 6T)    "
echo "============================================================"
echo ""
echo "This gate verifies read-only access to a production database."
echo "It DOES NOT switch the application's primary database."
echo ""
echo "To configure the gate securely on your VPS:"
echo "  nano .env"
echo ""
echo "Required settings:"
echo "  ALLOW_PRODUCTION_DB=true"
echo "  ENABLE_PRODUCTION_DB_READONLY_GATE=true"
echo "  PRODUCTION_DB_READONLY_REQUIRED=true"
echo "  PRODUCTION_DB_PATH=/path/to/production/tasi_ledger.db"
echo ""
echo "CRITICAL WARNINGS:"
echo "  - DB_PATH MUST REMAIN: DB_PATH=tasi_ledger_test.db"
echo "  - Do NOT paste paths or secrets into ChatGPT, AI Studio, GitHub, etc."
echo "  - Do NOT run this with a DB file unless it is a copied/backed-up production DB."
echo ""
echo "After configuring, verify the read-only connection status securely:"
echo "  bash scripts/db_gate_status.sh"
echo "  bash scripts/db_gate_readonly_preflight.sh"
echo "============================================================"
