#!/bin/bash
# scripts/live_preview_enable_notes.sh
# Phase 6U - Instructions for manual live preview

echo "============================================================"
echo "    Manual Live Preview Enablement Notes (Phase 6U)         "
echo "============================================================"
echo ""
echo "Live Preview allows you to test market data pipelines for Analyze"
echo "and Scout manually. It DOES NOT execute trades, run scheduled scans,"
echo "send Telegram alerts, or write to the production database."
echo ""
echo "To manually enable Live Preview on your VPS:"
echo "  nano .env"
echo ""
echo "Set these values to true:"
echo "  ENABLE_LIVE_ANALYZE_PREVIEW=true"
echo "  ENABLE_LIVE_SCOUT_PREVIEW=true"
echo ""
echo "CRITICAL WARNINGS:"
echo "  - ENABLE_ALERT_SCHEDULER MUST remain false."
echo "  - ENABLE_PROVIDER_COVERAGE_SCAN MUST remain false."
echo "  - ALLOW_PRODUCTION_DB MUST remain false."
echo "  - DB_PATH MUST remain tasi_ledger_test.db."
echo "  - Telegram sending remains strictly disabled."
echo "  - No order execution is allowed."
echo ""
echo "After configuring, verify the live preview status safely:"
echo "  bash scripts/live_preview_status.sh"
echo "============================================================"
