#!/bin/bash

echo "=========================================================="
echo " GHBS Private Restore Notes Checklist "
echo "=========================================================="
echo "To safely restore your GHBS application natively from a backup:"
echo ""
echo "1. STOP the Application gracefully:"
echo "   sudo bash scripts/private_app_ops.sh stop"
echo ""
echo "2. INSPECT the backup snapshot directory (e.g., backups/private_ops/YYYYMMDD_HHMMSS/)"
echo "   Ensure it contains valid files."
echo ""
echo "3. RESTORE .env (after safe review):"
echo "   cp backups/private_ops/YYYYMMDD_HHMMSS/.env .env"
echo "   -> VERY IMPORTANT: Check .env to ensure ALLOW_PRODUCTION_DB=false remains true to sandbox."
echo ""
echo "4. RESTORE Sandbox Test Database (if rolling back data):"
echo "   cp backups/private_ops/YYYYMMDD_HHMMSS/tasi_ledger_test.db tasi_ledger_test.db"
echo "   -> WARNING: DO NOT replace the real production database (tasi_ledger.db). This is for sandbox ONLY."
echo ""
echo "5. VALIDATE Release Integrity:"
echo "   bash scripts/validate_release.sh"
echo ""
echo "6. START Application Operations smoothly:"
echo "   sudo bash scripts/private_app_ops.sh start"
echo ""
echo "7. VERIFY Safety Access:"
echo "   bash scripts/private_public_exposure_check.sh"
echo "=========================================================="
exit 0
