#!/bin/bash
# scripts/provider_manual_smoke_notes.sh
# Phase 6V - Instructions for market data manual smoke tests

echo "============================================================"
echo "    Manual Provider Smoke Tests Enablement Notes (Phase 6V) "
echo "============================================================"
echo ""
echo "Market data provider smoke tests allow you to safely verify"
echo "API keys and provider connectivity (e.g. yfinance, TwelveData)"
echo "WITHOUT executing any trades, scans, or strategy logic."
echo ""
echo "To manually enable Smoke Tests on your VPS:"
echo "  nano .env"
echo ""
echo "Set this value to true:"
echo "  ENABLE_MARKET_DATA_SMOKE_TESTS=true"
echo ""
echo "CRITICAL WARNINGS:"
echo "  - ENABLE_ALERT_SCHEDULER MUST remain false."
echo "  - ENABLE_PROVIDER_COVERAGE_SCAN MUST remain false."
echo "  - ALLOW_PRODUCTION_DB MUST remain false."
echo "  - DB_PATH MUST remain tasi_ledger_test.db."
echo "  - ENABLE_LIVE_ANALYZE_PREVIEW MUST remain false (unless explicitly testing analyze flow)."
echo "  - No order execution is allowed."
echo ""
echo "After configuring, verify the provider status safely:"
echo "  bash scripts/provider_readiness_status.sh"
echo "============================================================"
